apiVersion: v1
kind: Service
metadata:
  name: rust-app-svc
spec:
  type: LoadBalancer
  selector:
    app: rust-app 

  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31200
