apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  POSTGRES_DB: postgres
  POSTGRES_PASSWORD: mainpassword
  POSTGRES_USER: mainuser
  DB_URL: postgresql://mainuser:mainpassword@tech-challenge-db.cra60s8i0ksr.us-east-1.rds.amazonaws.com:5432/TechChallengeDb
  MOCK_PAGAMENTOS_URL: http://afc76b109208f4d2c8d13208be73e8d3-1994566617.us-east-1.elb.amazonaws.com:9000/payment/
  API_HOST: http://a15a70588a4474d6eb8d89e8b2d2ae36-718246511.us-east-1.elb.amazonaws.com:3000