apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  POSTGRES_DB: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres
  DB_URL: postgres://postgres:postgres@db-svc:5432
  MOCK_PAGAMENTOS_URL: mock-pagamentos-svc:9000
  API_HOST: rust-app-svc:3000