apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    app: db-pod
spec:
  containers:
    - name: db
      image: postgres:15.2-alpine
      ports:
        - containerPort: 5432
      envFrom:
        - configMapRef:
            name: app-configmap