apiVersion: v1
kind: Pod
metadata:
  name: mock-pagamentos-pod
  labels:
    app: mock-pagamentos-pod
spec:
  containers:
    - name: mock-pagamentos
      image: brunomafra/mock-pagamentos:latest
      ports:
        - containerPort: 9000