version: '3'
services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile.dev
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db
  #   # volumes:
  #   #   - .:/app
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local