version: '3'
services:
  api:
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      DB_URL: "postgres://postgres:postgres@db:5432"
      SECRET: "secret_from_docker"
    depends_on:
      - db
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local