apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-rust-api
  labels: 
     app: rust-api

spec:
  replicas: 1 
  selector:
    matchLabels:
      app: rust-api

  template:
    metadata:
      labels:
        app: rust-api
    spec:
      containers:
      - name: rust-api
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1%
