apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-hello-app-service
  labels:
    app: rust-api
spec:
  selector:
    app: rust-api 

  ports:
    - port: 3000
      targetPort: 3000

  type: LoadBalancer
